version: '3.8'
services:
  backend:
    build: ./back
    ports:
      - 5000:5000
    volumes:
      - ./back:/app:ro
    restart: unless-stopped

  frontend:
    build: ./front
    ports:
      - 3000:80
    depends_on:
      - backend
    restart: unless-stopped
